name: Deploy Backend to VPS

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy Backend to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "🚀 Начинаем обновление бэкенда..."
          
          # Переходим в директорию проекта
          cd /home/${{ secrets.VPS_USERNAME }}/career-miniapp || {
            echo "❌ Директория проекта не найдена"
            exit 1
          }
          
          # Создаем backup текущей версии
          if [ -d "backend" ]; then
            cp -r backend backend.backup.$(date +%Y%m%d_%H%M%S)
            echo "✅ Backup создан"
          fi
          
          # Обновляем код из Git
          git fetch origin
          git reset --hard origin/main
          echo "✅ Код обновлен из Git"
          
          # Переходим в директорию бэкенда
          cd backend
          
          # Активируем виртуальное окружение
          source venv/bin/activate
          
          # Обновляем зависимости
          pip install -r requirements.txt
          echo "✅ Зависимости обновлены"
          
          # Проверяем, что httpx версия правильная
          pip show httpx | grep Version
          
          # Перезапускаем сервис
          sudo systemctl restart career-backend
          echo "✅ Сервис перезапущен"
          
          # Ждем несколько секунд для запуска
          sleep 5
          
          # Проверяем статус сервиса
          if sudo systemctl is-active --quiet career-backend; then
            echo "✅ Сервис работает"
          else
            echo "❌ Сервис не запустился"
            sudo systemctl status career-backend
            exit 1
          fi
          
          # Проверяем health endpoint
          if curl -f http://localhost:8000/health > /dev/null 2>&1; then
            echo "✅ Health check прошел"
          else
            echo "❌ Health check не прошел"
            exit 1
          fi
          
          echo "🎉 Деплой бэкенда завершен успешно!"