name: Deploy Backend to VPS

on:
  workflow_dispatch:  # Временно отключаем автозапуск, только ручной
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'backend/**'
  #     - '.github/workflows/deploy-backend.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy Backend to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "🚀 Начинаем обновление бэкенда..."
          
          # Останавливаем сервис
          sudo systemctl stop career-backend || echo "Сервис уже остановлен"
          
          # Создаем backup текущей версии
          if [ -d "/opt/career-backend" ] && [ "$(ls -A /opt/career-backend)" ]; then
            sudo cp -r /opt/career-backend /opt/career-backend.backup.$(date +%Y%m%d_%H%M%S)
            echo "✅ Backup создан"
          fi
          
          # Переходим во временную директорию
          cd /tmp
          
          # Клонируем свежую версию репозитория
          rm -rf career-miniapp
          git clone https://github.com/${{ github.repository }}.git career-miniapp
          
          # Копируем новый backend
          sudo cp -r career-miniapp/backend/* /opt/career-backend/
          
          # Переходим в директорию бэкенда
          cd /opt/career-backend
          
          # Создаем виртуальное окружение если его нет
          if [ ! -d "venv" ]; then
            sudo python3 -m venv venv
          fi
          
          # Обновляем pip и устанавливаем зависимости
          sudo venv/bin/pip install --upgrade pip
          sudo venv/bin/pip install --no-cache-dir --force-reinstall -r requirements.txt
          echo "✅ Зависимости обновлены"
          
          # Проверяем версию httpx
          sudo venv/bin/python -c "import httpx; print(f'httpx version: {httpx.__version__}')"
          
          # Устанавливаем правильные права доступа
          sudo chown -R www-data:www-data /opt/career-backend
          
          # Запускаем сервис
          sudo systemctl start career-backend
          echo "✅ Сервис запущен"
          
          # Ждем запуска
          sleep 10
          
          # Проверяем статус сервиса
          if sudo systemctl is-active --quiet career-backend; then
            echo "✅ Сервис работает"
          else
            echo "❌ Сервис не запустился"
            sudo systemctl status career-backend
            sudo journalctl -u career-backend --no-pager -n 20
            exit 1
          fi
          
          # Проверяем health endpoint
          sleep 5
          if curl -f http://localhost:8000/health > /dev/null 2>&1; then
            echo "✅ Health check прошел"
          else
            echo "❌ Health check не прошел"
            curl -v http://localhost:8000/health || true
            exit 1
          fi
          
          # Очищаем временные файлы
          rm -rf /tmp/career-miniapp
          
          echo "🎉 Деплой бэкенда завершен успешно!"