name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/miniapp
          git pull origin main
          
          # Stop existing containers
          docker-compose -f docker-compose.prod.yml down || true
          
          # Create .env.prod file with secrets
          cat > .env.prod << EOF
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          DOMAIN=raputitechit.beget.app
          POSTGRES_DB=career_miniapp
          POSTGRES_USER=postgres
          POSTGRES_HOST=postgres
          POSTGRES_PORT=5432
          DATABASE_URL=postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/career_miniapp
          ENVIRONMENT=production
          EOF
          
          # Build and start containers
          docker-compose -f docker-compose.prod.yml up -d --build
          
          # Wait for services to start
          sleep 30
          
          # Check if API is responding
          curl -f http://localhost:8000/health || exit 1
          
          # Clean up old images
          docker image prune -f